import React, { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, Sun, Globe2, Heart, Palette, FlaskConical, Music2, Trophy, Menu, X, Check, Download, MapPin, Clock, Sparkles, ChevronDown } from 'lucide-react';
import './styles.css';

const programmes = [
 {name:'Early Years',age:'A joyful beginning',icon:Sun,color:'yellow',description:'Play, stories, and hands-on discovery help little learners build confidence, curiosity, and friendships.',subjects:['Learning through play','Language & expression','Movement & creativity']},
 {name:'Primary School',age:'Strong foundations',icon:BookOpen,color:'orange',description:'Meaningful lessons connect reading, mathematics, and the world around us, one discovery at a time.',subjects:['Literacy & numeracy','Environmental learning','Art & physical education']},
 {name:'Middle & Secondary',age:'Ready for what’s next',icon:Globe2,color:'blue',description:'Independent thinking, deeper subject exploration, and collaborative projects prepare learners for their next chapter.',subjects:['Science & mathematics','Languages & humanities','Projects & life skills']}
];
const activities=[{icon:FlaskConical,title:'Wonder. Test. Discover.',type:'Science & discovery',body:'Big questions become hands-on experiments. A space to think, try, and learn from every result.'},{icon:Palette,title:'A little colour. A lot of imagination.',type:'Art & expression',body:'From a first sketch to a shared performance, creativity gives every child a voice.'},{icon:Trophy,title:'Team spirit starts here.',type:'Sports & wellbeing',body:'Move with confidence, play with purpose, and discover the joy of working together.'}];
function App(){
 const [menu,setMenu]=useState(false),[selected,setSelected]=useState(null),[filter,setFilter]=useState('All programmes'),[faq,setFaq]=useState(0),[saved,setSaved]=useState(false);
 const [form,setForm]=useState({parent:'',email:'',phone:'',programme:'',message:''});
 useEffect(()=>{
   if(!selected)return;
   const previous=document.activeElement;
   const overflow=document.body.style.overflow;
   document.body.style.overflow='hidden';
   const handleKey=e=>{
     if(e.key==='Escape'){setSelected(null);return;}
     if(e.key!=='Tab')return;
     const items=document.querySelectorAll('.modal button, .modal a');
     const first=items[0],last=items[items.length-1];
     if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}
     else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}
   };
   document.addEventListener('keydown',handleKey);
   return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',handleKey);previous?.focus();};
 },[selected]);
 const nav=['About','Programmes','School Life','Admissions'];
 const id=(s)=>s.toLowerCase().replaceAll(' ','-');
 const update=e=>{setSaved(false);setForm({...form,[e.target.name]:e.target.value})};
 const submit=e=>{e.preventDefault();const text=`ASHA International School — Admissions enquiry\n\nParent / guardian: ${form.parent}\nEmail: ${form.email}\nPhone: ${form.phone}\nProgramme: ${form.programme}\nMessage: ${form.message}\n\nThis enquiry has been prepared locally. Please share it directly with the school admissions office.`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='ASHA-admissions-enquiry.txt';a.click();URL.revokeObjectURL(url);setSaved(true)};
 return <><header><div className="container header-top"><a className="brand" href="#home" aria-label="ASHA International School home"><img src="/logo.svg" alt="ASHA International School"/></a><div className="header-note"><span className="mini-icon"><Heart size={19}/></span><div><strong>A place to belong</strong><span>A world of possibilities</span></div></div><div className="header-note"><span className="mini-icon"><Globe2 size={19}/></span><div><strong>Rooted in values</strong><span>Inspired by the world</span></div></div><a href="#admissions" className="button small">Explore admissions</a><button className="menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div><div className="container nav-row"><nav className={menu?'open':''} aria-label="Main navigation"><a href="#home" className="active" onClick={()=>setMenu(false)}>Home</a>{nav.map(n=><a key={n} href={'#'+id(n)} onClick={()=>setMenu(false)}>{n}</a>)}<a href="#contact" onClick={()=>setMenu(false)}>Contact</a></nav><span className="nav-motto">Learn. Explore. Grow.</span></div></header>
 <main><section id="home" className="hero"><div className="hero-wash"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span/> SMALL STEPS. EXTRAORDINARY FUTURES.</div><h1>A world of learning.<br/>A future full of <span>possibilities.</span></h1><p>At ASHA International School, curious minds find their spark. A caring community where every child is encouraged to learn, explore, and become their best self.</p><div className="hero-buttons"><a className="button" href="#admissions">Begin your ASHA journey</a><a className="text-link" href="#about">Discover our school <span className="play">▷</span></a></div><div className="hero-foot"><span className="tiny-sun">✳</span><span>Big dreams begin with a little curiosity.</span></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="dot dot-orange"/><span className="dot dot-yellow"/><span className="star">✳</span><div className="photo-circle"><img src="/learning.jpg" alt="Children exploring their lessons together in a classroom"/></div><div className="floating-card"><span className="float-icon"><BookOpen size={24}/></span><div><strong>Learning for life</strong><small>Growing beyond the classroom</small></div></div><div className="little-tag"><Sparkles size={17}/> Every child, a possibility.</div></div></div><span className="watermark" aria-hidden="true">ASHA</span></section>
 <section className="values-strip container" aria-label="Our values">{[{icon:BookOpen,title:'Learning with purpose',body:'Knowledge that opens doors'},{icon:Heart,title:'Growing with care',body:'Every child feels seen'},{icon:Globe2,title:'Thinking beyond borders',body:'Local roots. Global outlook.'}].map(({icon:Icon,title,body},i)=><div className="value" key={title}><span className={'value-icon v'+i}><Icon size={25}/></span><div><h3>{title}</h3><p>{body}</p></div></div>)}</section>
 <section id="about" className="section container about"><div className="about-visual"><div className="about-photo"><img src="/learning.jpg" alt="Young learners building confidence through daily learning" loading="lazy"/></div><div className="about-label"><Heart size={23}/><span>A happy place<br/><strong>to learn & grow.</strong></span></div><span className="about-dots" aria-hidden="true">· · · ·<br/>· · · ·<br/>· · · ·</span></div><div className="about-copy"><div className="eyebrow">WELCOME TO ASHA</div><h2>More than a school.<br/><span>A place to flourish.</span></h2><p>Education begins with a sense of belonging. Our vision is a welcoming learning community that nurtures confidence, celebrates individuality, and makes room for every child’s potential.</p><p>We bring academic learning together with creativity, compassion, and real-world discovery — helping children grow as thoughtful learners and kind human beings.</p><ul className="check-list"><li><Check size={17}/> A child-centred approach to learning</li><li><Check size={17}/> Curiosity, creativity, and strong values</li><li><Check size={17}/> A partnership between school and family</li></ul><a href="#programmes" className="button secondary">Explore the learning journey</a></div></section>
 <section id="programmes" className="programme-section section"><div className="container"><div className="section-top"><div><div className="eyebrow">ROOM TO GROW, AT EVERY STAGE</div><h2>A journey of <span>discovery.</span></h2></div><label className="filter">Explore programmes<select value={filter} onChange={e=>setFilter(e.target.value)}><option>All programmes</option>{programmes.map(p=><option key={p.name}>{p.name}</option>)}</select></label></div><div className="programme-grid">{programmes.filter(p=>filter==='All programmes'||p.name===filter).map(({icon:Icon,...p},i)=><article className={'programme-card '+p.color} key={p.name}><div className="programme-art"><span className="programme-number">0{programmes.findIndex(x=>x.name===p.name)+1}</span><Icon size={69} strokeWidth={1.3}/><span className="art-spark">✳</span></div><div className="programme-content"><small>{p.age}</small><h3>{p.name}</h3><p>{p.description}</p><button className="card-link" onClick={()=>setSelected({...p,icon:Icon})}>Discover programme <span>+</span></button></div></article>)}</div></div></section>
 <section id="school-life" className="section container school-life"><div className="center-heading"><div className="eyebrow">BEYOND THE CLASSROOM</div><h2>Little moments.<br/><span>Big discoveries.</span></h2><p>Room to create, space to play, and endless reasons to be curious.<br/>Learning comes alive when children get involved.</p></div><div className="activity-grid">{activities.map(({icon:Icon,title,type,body},i)=><article className="activity" key={title}><span className={'activity-icon a'+i}><Icon size={34}/></span><small>{type}</small><h3>{title}</h3><p>{body}</p></article>)}</div><div className="quote-banner"><Music2 size={42}/><p>“Every child carries a spark.<br/><strong>Our purpose is to help it shine.</strong>”</p><span>THE ASHA SPIRIT</span></div></section>
 <section id="admissions" className="section admissions"><div className="container admissions-grid"><div><div className="eyebrow">LET’S BEGIN SOMETHING WONDERFUL</div><h2>The next chapter<br/>starts with <span>ASHA.</span></h2><p>Choosing a school is a big step. Start by telling us a little about your family and the learning stage you’re interested in.</p><ol className="steps"><li><span>01</span><div><h3>Explore our programmes</h3><p>Find the right starting point for your child.</p></div></li><li><span>02</span><div><h3>Prepare your enquiry</h3><p>Save your details to share with the school.</p></div></li><li><span>03</span><div><h3>Meet the school team</h3><p>Discuss availability, a visit, and the next steps.</p></div></li></ol></div><form onSubmit={submit} className="enquiry-form"><h3>Let’s get to know you.</h3><p>Prepare an admissions enquiry</p><label>Parent / guardian name<input name="parent" autoComplete="name" required value={form.parent} onChange={update} placeholder="Your full name"/></label><div className="form-row"><label>Email address<input type="email" name="email" autoComplete="email" required value={form.email} onChange={update} placeholder="you@example.com"/></label><label>Phone number<input type="tel" name="phone" autoComplete="tel" value={form.phone} onChange={update} placeholder="Your phone number"/></label></div><label>Interested programme<select name="programme" required value={form.programme} onChange={update}><option value="">Select a programme</option>{programmes.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>Anything you’d like to ask?<textarea name="message" value={form.message} onChange={update} placeholder="Tell us a little about your child or your questions" rows="3"/></label><button type="submit" className="button"><Download size={17}/> Save my enquiry</button><p className="form-note">Your details stay on your device. This downloads your enquiry; it does not send it to the school.</p>{saved&&<div className="success" role="status"><Check size={19}/> Enquiry prepared. Share the downloaded file with the school admissions team.</div>}</form></div></section>
 <section className="section container faq-section"><div><div className="eyebrow">A LITTLE MORE TO KNOW</div><h2>Questions?<br/><span>Start here.</span></h2></div><div className="faq-list">{[{q:'How can I enquire about admission?',a:'Choose a programme and complete the enquiry form above. Save the enquiry file and share it with the school admissions office. The team can confirm class availability, documents, fees, and the admissions process.'},{q:'Can we visit the school before applying?',a:'A school visit is a helpful way to get to know the learning environment. Please arrange a visit directly with the school team once the official contact details are available.'},{q:'Where can I find fees and curriculum details?',a:'Confirmed curriculum, affiliation, class availability, and fee information should be obtained directly from the school admissions office.'}].map((item,i)=><div className="faq" key={item.q}><button aria-expanded={faq===i} aria-controls={'faq-'+i} onClick={()=>setFaq(faq===i?null:i)}>{item.q}<ChevronDown size={20} className={faq===i?'rotated':''}/></button>{faq===i&&<p id={'faq-'+i}>{item.a}</p>}</div>)}</div></section>
 <section className="closing container"><span className="closing-spark">✳</span><div><small>A BRIGHTER TOMORROW STARTS TODAY</small><h2>Let curiosity lead the way.</h2></div><a href="#admissions" className="button">Explore admissions</a></section></main>
 <footer id="contact"><div className="container footer-grid"><div><a href="#home"><img className="footer-logo" src="/logo.svg" alt="ASHA International School"/></a><p>Curious minds. Kind hearts.<br/>A world of possibilities.</p><a className="download-logo" href="/logo.svg" download="ASHA-logo.svg"><Download size={15}/> Download school logo</a></div><div><h3>Explore ASHA</h3>{nav.map(n=><a href={'#'+id(n)} key={n}>{n}</a>)}</div><div><h3>Start a conversation</h3><p>For admissions, school visits,<br/>and programme information.</p><a href="#admissions" className="text-link">Prepare an enquiry</a><span className="contact-note">Official contact details to be added.</span></div><div className="footer-motto"><img src="/logo-mark.svg" alt=""/><h3>Learn.<br/>Explore.<br/><span>Grow.</span></h3></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} ASHA International School.</span><span>With curiosity. With care.</span></div></footer>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="programme-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSelected(null)}}><button autoFocus className="modal-close" aria-label="Close programme details" onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">THE ASHA LEARNING JOURNEY</span><h2 id="programme-title">{selected.name}</h2><p>{selected.description}</p><h3>Areas of exploration</h3><ul className="check-list">{selected.subjects.map(s=><li key={s}><Check size={17}/>{s}</li>)}</ul><p className="modal-note">Contact the school for confirmed classes, curriculum, and availability.</p><a className="button" href="#admissions" onClick={()=>{setForm({...form,programme:selected.name});setSelected(null)}}>Enquire about this programme</a></section></div>}
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);
