import React, { useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, Sun, Globe2, Heart, Palette, FlaskConical, Music2, Trophy, Menu, X, Check, Download, MapPin, Clock, Phone, Search, ChevronDown, GraduationCap, Atom, Backpack } from 'lucide-react';
import './styles.css';

const programmes = [
 {name:'Early Years',age:'A joyful beginning',icon:Sun,color:'yellow',description:'Play, stories, and hands-on discovery help little learners build confidence, curiosity, and friendships.',subjects:['Learning through play','Language & expression','Movement & creativity']},
 {name:'Primary School',age:'Strong foundations',icon:BookOpen,color:'orange',description:'Meaningful lessons connect reading, mathematics, and the world around us, one discovery at a time.',subjects:['Literacy & numeracy','Environmental learning','Art & physical education']},
 {name:'Middle & Secondary',age:'Ready for what’s next',icon:Globe2,color:'blue',description:'Independent thinking, deeper subject exploration, and collaborative projects prepare learners for their next chapter.',subjects:['Science & mathematics','Languages & humanities','Projects & life skills']}
];
const activities=[{icon:FlaskConical,title:'Wonder. Test. Discover.',type:'Science & discovery',body:'Big questions become hands-on experiments. A space to think, try, and learn from every result.'},{icon:Palette,title:'A little colour. A lot of imagination.',type:'Art & expression',body:'From a first sketch to a shared performance, creativity gives every child a voice.'},{icon:Trophy,title:'Team spirit starts here.',type:'Sports & wellbeing',body:'Move with confidence, play with purpose, and discover the joy of working together.'}];
const schoolContact = { phone: '+91 9958584710', tel: 'tel:+919958584710', address: 'L128, Street No 03, New Delhi, Delhi' };
// Add the school's official profile URLs here to activate the social links.
const socialProfiles = [{ name: 'Facebook', url: '' }, { name: 'LinkedIn', url: '' }, { name: 'Instagram', url: '' }];
function SocialIcon({name}){
 return <svg className="social-icon" width="20" height="20" viewBox="0 0 24 24" aria-hidden="true" focusable="false">{name==='Facebook'?<path fill="currentColor" d="M14 22v-9h3l.5-4H14V6.5c0-1 .3-1.5 1.7-1.5H18V1.4c-.4-.1-1.8-.4-3.5-.4C11 1 9 3.1 9 6.7V9H6v4h3v9z"/>:name==='LinkedIn'?<><path fill="currentColor" d="M3 8h4v14H3zM10 8h4v2c.8-1.4 2-2.3 4-2.3 4 0 4 3.4 4 6.2V22h-4v-7.2c0-1.8 0-3.6-2-3.6s-2 1.8-2 3.5V22h-4z"/><circle cx="5" cy="3.5" r="2.3" fill="currentColor"/></>:<><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="17.5" cy="6.5" r="1.3" fill="currentColor"/></>}</svg>;
}
function SocialLinks(){return <div className="social-links" aria-label="School social profiles">{socialProfiles.map(({name,url})=>url?<a key={name} href={url} target="_blank" rel="noopener noreferrer" aria-label={name}><SocialIcon name={name}/></a>:<span key={name} className="social-pending" role="img" aria-label={name+' — profile link pending'} title={name+' — profile link pending'}><SocialIcon name={name}/></span>)}</div>;}
function App(){
 const [menu,setMenu]=useState(false),[selected,setSelected]=useState(null),[filter,setFilter]=useState('All programmes'),[faq,setFaq]=useState(0),[saved,setSaved]=useState(false);
 const [search,setSearch]=useState(''),[searchMessage,setSearchMessage]=useState('');
 const [form,setForm]=useState({parent:'',email:'',phone:'',programme:'',message:''});
 useEffect(()=>{
   if(!selected)return;
   const previous=document.activeElement;
   const overflow=document.body.style.overflow;
   document.body.style.overflow='hidden';
   const handleKey=e=>{
     if(e.key==='Escape'){setSelected(null);return;}
     if(e.key!=='Tab')return;
     const items=document.querySelectorAll('.modal button, .modal a');
     const first=items[0],last=items[items.length-1];
     if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}
     else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}
   };
   document.addEventListener('keydown',handleKey);
   return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',handleKey);previous?.focus();};
 },[selected]);
 const nav=['About','Programmes','School Life','Admissions'];
 const id=(s)=>s.toLowerCase().replaceAll(' ','-');
 const update=e=>{setSaved(false);setForm({...form,[e.target.name]:e.target.value})};
 const searchProgrammes=e=>{e.preventDefault();const query=search.trim().toLowerCase();const match=programmes.find(p=>(p.name+' '+p.age+' '+p.description+' '+p.subjects.join(' ')).toLowerCase().includes(query));if(!query){setFilter('All programmes');setSearchMessage('');}else if(match){setFilter(match.name);setSearchMessage('');}else{setFilter('All programmes');setSearchMessage('No exact match. Explore all three programmes below.');}document.getElementById('programmes')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};
 const submit=e=>{e.preventDefault();const text=`ASHA International School — Admissions enquiry\n\nParent / guardian: ${form.parent}\nEmail: ${form.email}\nPhone: ${form.phone}\nProgramme: ${form.programme}\nMessage: ${form.message}\n\nThis enquiry has been prepared locally. Please share it directly with the school admissions office.`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='ASHA-admissions-enquiry.txt';a.click();URL.revokeObjectURL(url);setSaved(true)};
 return <><header><div className="container header-top"><a className="brand" href="#home" aria-label="ASHA International School home"><img src="/logo.svg" alt="ASHA International School"/></a><div className="header-contacts"><div className="header-note"><span className="mini-icon"><Phone size={21}/></span><div><strong>Call</strong><a href={schoolContact.tel}>{schoolContact.phone}</a></div></div><div className="header-note"><span className="mini-icon"><Clock size={21}/></span><div><strong>Work Time</strong><span>Mon - Sat 8 AM - 5 PM</span></div></div><div className="header-note address-note"><span className="mini-icon"><MapPin size={21}/></span><div><strong>Address</strong><span>{schoolContact.address}</span></div></div></div><button className="menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div><div className="container nav-row"><nav className={menu?'open':''} aria-label="Main navigation"><a href="#home" className="active" onClick={()=>setMenu(false)}>Home</a>{nav.map(n=><a key={n} href={'#'+id(n)} onClick={()=>setMenu(false)}>{n}</a>)}<a href="#contact" onClick={()=>setMenu(false)}>Contact</a></nav><SocialLinks/></div></header>
 <main><section id="home" className="hero hero-refined"><div className="hero-wash"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span/> ASHA INTERNATIONAL SCHOOL</div><h1>A brighter way<br/>to learn <span>& grow.</span></h1><p>Big ideas begin with curious minds. At ASHA, we bring learning, creativity, and care together — helping every child discover a world of possibilities.</p><form className="hero-search" role="search" onSubmit={searchProgrammes}><label className="sr-only" htmlFor="programme-search">Search school programmes</label><input id="programme-search" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a programme for your child"/><button type="submit" aria-label="Search programmes"><Search size={22}/></button></form><div className="hero-quick-links"><a href="#programmes" onClick={()=>setFilter('Early Years')}>Early Years</a><span>·</span><a href="#programmes" onClick={()=>setFilter('Primary School')}>Primary</a><span>·</span><a href="#programmes" onClick={()=>setFilter('Middle & Secondary')}>Middle & Secondary</a></div><a className="hero-admissions" href="#admissions">Begin your ASHA journey</a></div><div className="hero-art" aria-label="A world of learning"><div className="hero-photo photo-mentor"><img src="/hero-classroom.jpg" alt="A teacher guiding children through a classroom lesson" fetchPriority="high"/></div><div className="hero-photo photo-discovery"><img src="/hero-discovery.jpg" alt="Children discovering new ideas with their teacher"/></div><div className="hero-photo photo-friends"><img src="/hero-together.jpg" alt="Young learners working together at a classroom desk"/></div><div className="hero-photo photo-small"><img src="/learning.jpg" alt="A young learner concentrating on a lesson"/></div><span className="hero-bubble bubble-orange"/><span className="hero-bubble bubble-yellow"/><span className="hero-bubble bubble-gradient"/><span className="hero-bubble bubble-small"/></div></div><span className="watermark" aria-hidden="true">ASHA</span></section>
 <section className="values-strip container" aria-label="Our values">{[{icon:BookOpen,title:'Learning with purpose',body:'Knowledge that opens doors'},{icon:Heart,title:'Growing with care',body:'Every child feels seen'},{icon:Globe2,title:'Thinking beyond borders',body:'Local roots. Global outlook.'}].map(({icon:Icon,title,body},i)=><div className="value" key={title}><span className={'value-icon v'+i}><Icon size={25}/></span><div><h3>{title}</h3><p>{body}</p></div></div>)}</section>
 <section id="welcome" className="section container welcome-section" aria-labelledby="welcome-heading"><div className="center-heading"><h2 id="welcome-heading">Welcome to <span>ASHA</span></h2><p>A world of curiosity, a community of care.<br/>Discover the little things that make learning meaningful.</p></div><div className="welcome-features">{[{icon:GraduationCap,title:'Inspiring Teachers',body:'Guidance that encourages questions, builds confidence, and brings lessons to life.'},{icon:Globe2,title:'A Global Outlook',body:'Learning to understand the world with an open mind and respect for others.'},{icon:Atom,title:'Meaningful Learning',body:'Strong foundations, hands-on discovery, and space for creative thinking.'},{icon:Backpack,title:'Care at Every Step',body:'A welcoming environment where children feel supported as they learn and grow.'}].map(({icon:Icon,title,body},i)=><article className="welcome-feature" key={title}><Icon size={37} strokeWidth={1.35} className={i%2?'feature-blue':'feature-orange'}/><h3>{title}</h3><p>{body}</p></article>)}</div><div className="welcome-mosaic" aria-label="Moments of learning and discovery"><div className="mosaic-photo mosaic-one"><img src="/learning.jpg" alt="A child focused on a classroom lesson" loading="lazy"/></div><div className="mosaic-photo mosaic-two"><img src="/hero-discovery.jpg" alt="A teacher supporting children as they learn" loading="lazy"/></div><div className="mosaic-photo mosaic-three"><img src="/hero-together.jpg" alt="Students sharing a moment of discovery" loading="lazy"/></div><div className="mosaic-photo mosaic-four"><img src="/hero-classroom.jpg" alt="Children taking part in a classroom lesson" loading="lazy"/></div><div className="mosaic-photo mosaic-five"><img src="/hero-together.jpg" alt="A closer look at a young learner working at a desk" loading="lazy"/></div><div className="mosaic-photo mosaic-six"><img src="/hero-discovery.jpg" alt="A colourful classroom filled with learning activities" loading="lazy"/></div><span className="mosaic-accent accent-striped" aria-hidden="true"/><span className="mosaic-accent accent-large" aria-hidden="true"/><span className="mosaic-accent accent-small" aria-hidden="true"/><span className="mosaic-accent accent-ring" aria-hidden="true"/></div></section>
 <section id="about" className="section container about"><div className="about-visual"><div className="about-photo"><img src="/learning.jpg" alt="Young learners building confidence through daily learning" loading="lazy"/></div><div className="about-label"><Heart size={23}/><span>A happy place<br/><strong>to learn & grow.</strong></span></div><span className="about-dots" aria-hidden="true">· · · ·<br/>· · · ·<br/>· · · ·</span></div><div className="about-copy"><div className="eyebrow">WELCOME TO ASHA</div><h2>More than a school.<br/><span>A place to flourish.</span></h2><p>Education begins with a sense of belonging. Our vision is a welcoming learning community that nurtures confidence, celebrates individuality, and makes room for every child’s potential.</p><p>We bring academic learning together with creativity, compassion, and real-world discovery — helping children grow as thoughtful learners and kind human beings.</p><ul className="check-list"><li><Check size={17}/> A child-centred approach to learning</li><li><Check size={17}/> Curiosity, creativity, and strong values</li><li><Check size={17}/> A partnership between school and family</li></ul><a href="#programmes" className="button secondary">Explore the learning journey</a></div></section>
 <section id="programmes" className="programme-section section"><div className="container"><div className="section-top"><div><div className="eyebrow">ROOM TO GROW, AT EVERY STAGE</div><h2>A journey of <span>discovery.</span></h2></div><label className="filter">Explore programmes<select value={filter} onChange={e=>setFilter(e.target.value)}><option>All programmes</option>{programmes.map(p=><option key={p.name}>{p.name}</option>)}</select></label></div>{searchMessage&&<p className="search-message" role="status">{searchMessage}</p>}<div className="programme-grid">{programmes.filter(p=>filter==='All programmes'||p.name===filter).map(({icon:Icon,...p},i)=><article className={'programme-card '+p.color} key={p.name}><div className="programme-art"><span className="programme-number">0{programmes.findIndex(x=>x.name===p.name)+1}</span><Icon size={69} strokeWidth={1.3}/><span className="art-spark">✳</span></div><div className="programme-content"><small>{p.age}</small><h3>{p.name}</h3><p>{p.description}</p><button className="card-link" onClick={()=>setSelected({...p,icon:Icon})}>Discover programme <span>+</span></button></div></article>)}</div></div></section>
 <section id="school-life" className="section container school-life"><div className="center-heading"><div className="eyebrow">BEYOND THE CLASSROOM</div><h2>Little moments.<br/><span>Big discoveries.</span></h2><p>Room to create, space to play, and endless reasons to be curious.<br/>Learning comes alive when children get involved.</p></div><div className="activity-grid">{activities.map(({icon:Icon,title,type,body},i)=><article className="activity" key={title}><span className={'activity-icon a'+i}><Icon size={34}/></span><small>{type}</small><h3>{title}</h3><p>{body}</p></article>)}</div><div className="quote-banner"><Music2 size={42}/><p>“Every child carries a spark.<br/><strong>Our purpose is to help it shine.</strong>”</p><span>THE ASHA SPIRIT</span></div></section>
 <section id="admissions" className="section admissions"><div className="container admissions-grid"><div><div className="eyebrow">LET’S BEGIN SOMETHING WONDERFUL</div><h2>The next chapter<br/>starts with <span>ASHA.</span></h2><p>Choosing a school is a big step. Start by telling us a little about your family and the learning stage you’re interested in.</p><ol className="steps"><li><span>01</span><div><h3>Explore our programmes</h3><p>Find the right starting point for your child.</p></div></li><li><span>02</span><div><h3>Prepare your enquiry</h3><p>Save your details to share with the school.</p></div></li><li><span>03</span><div><h3>Meet the school team</h3><p>Discuss availability, a visit, and the next steps.</p></div></li></ol></div><form onSubmit={submit} className="enquiry-form"><h3>Let’s get to know you.</h3><p>Prepare an admissions enquiry</p><label>Parent / guardian name<input name="parent" autoComplete="name" required value={form.parent} onChange={update} placeholder="Your full name"/></label><div className="form-row"><label>Email address<input type="email" name="email" autoComplete="email" required value={form.email} onChange={update} placeholder="you@example.com"/></label><label>Phone number<input type="tel" name="phone" autoComplete="tel" value={form.phone} onChange={update} placeholder="Your phone number"/></label></div><label>Interested programme<select name="programme" required value={form.programme} onChange={update}><option value="">Select a programme</option>{programmes.map(p=><option key={p.name}>{p.name}</option>)}</select></label><label>Anything you’d like to ask?<textarea name="message" value={form.message} onChange={update} placeholder="Tell us a little about your child or your questions" rows="3"/></label><button type="submit" className="button"><Download size={17}/> Save my enquiry</button><p className="form-note">Your details stay on your device. This downloads your enquiry; it does not send it to the school.</p>{saved&&<div className="success" role="status"><Check size={19}/> Enquiry prepared. Share the downloaded file with the school admissions team.</div>}</form></div></section>
 <section className="section container faq-section"><div><div className="eyebrow">A LITTLE MORE TO KNOW</div><h2>Questions?<br/><span>Start here.</span></h2></div><div className="faq-list">{[{q:'How can I enquire about admission?',a:'Choose a programme and complete the enquiry form above. Save the enquiry file and share it with the school admissions office. The team can confirm class availability, documents, fees, and the admissions process.'},{q:'Can we visit the school before applying?',a:'A school visit is a helpful way to get to know the learning environment. Please call +91 9958584710 to arrange a visit with the school team at L128, Street No 03, New Delhi, Delhi.'},{q:'Where can I find fees and curriculum details?',a:'Confirmed curriculum, affiliation, class availability, and fee information should be obtained directly from the school admissions office.'}].map((item,i)=><div className="faq" key={item.q}><button aria-expanded={faq===i} aria-controls={'faq-'+i} onClick={()=>setFaq(faq===i?null:i)}>{item.q}<ChevronDown size={20} className={faq===i?'rotated':''}/></button>{faq===i&&<p id={'faq-'+i}>{item.a}</p>}</div>)}</div></section>
 <section className="closing container"><span className="closing-spark">✳</span><div><small>A BRIGHTER TOMORROW STARTS TODAY</small><h2>Let curiosity lead the way.</h2></div><a href="#admissions" className="button">Explore admissions</a></section></main>
 <footer id="contact"><div className="container footer-grid"><div><a href="#home"><img className="footer-logo" src="/logo.svg" alt="ASHA International School"/></a><p>Curious minds. Kind hearts.<br/>A world of possibilities.</p><a className="download-logo" href="/logo.svg" download="ASHA-logo.svg"><Download size={15}/> Download school logo</a></div><div><h3>Explore ASHA</h3>{nav.map(n=><a href={'#'+id(n)} key={n}>{n}</a>)}</div><div><h3>Start a conversation</h3><p>For admissions, school visits,<br/>and programme information.</p><a href="#admissions" className="text-link">Prepare an enquiry</a><a className="footer-contact" href={schoolContact.tel}><Phone size={16}/>{schoolContact.phone}</a><span className="footer-contact"><MapPin size={16}/>{schoolContact.address}</span><SocialLinks/></div><div className="footer-motto"><img src="/logo-mark.svg" alt=""/><h3>Learn.<br/>Explore.<br/><span>Grow.</span></h3></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} ASHA International School.</span><span>With curiosity. With care.</span></div></footer>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="programme-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSelected(null)}}><button autoFocus className="modal-close" aria-label="Close programme details" onClick={()=>setSelected(null)}><X/></button><span className="eyebrow">THE ASHA LEARNING JOURNEY</span><h2 id="programme-title">{selected.name}</h2><p>{selected.description}</p><h3>Areas of exploration</h3><ul className="check-list">{selected.subjects.map(s=><li key={s}><Check size={17}/>{s}</li>)}</ul><p className="modal-note">Contact the school for confirmed classes, curriculum, and availability.</p><a className="button" href="#admissions" onClick={()=>{setForm({...form,programme:selected.name});setSelected(null)}}>Enquire about this programme</a></section></div>}
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);
